export const TEAM_NAMES: Record<string, string> = {
  ARI: 'Arizona Cardinals',
  ATL: 'Atlanta Falcons',
  BAL: 'Baltimore Ravens',
  BUF: 'Buffalo Bills',
  CAR: 'Carolina Panthers',
  CHI: 'Chicago Bears',
  CIN: 'Cincinnati Bengals',
  CLE: 'Cleveland Browns',
  DAL: 'Dallas Cowboys',
  DEN: 'Denver Broncos',
  DET: 'Detroit Lions',
  GB:  'Green Bay Packers',
  HOU: 'Houston Texans',
  IND: 'Indianapolis Colts',
  JAX: 'Jacksonville Jaguars',
  KC:  'Kansas City Chiefs',
  LAC: 'Los Angeles Chargers',
  LAR: 'Los Angeles Rams',
  LV:  'Las Vegas Raiders',
  MIA: 'Miami Dolphins',
  MIN: 'Minnesota Vikings',
  NE:  'New England Patriots',
  NO:  'New Orleans Saints',
  NYG: 'New York Giants',
  NYJ: 'New York Jets',
  PHI: 'Philadelphia Eagles',
  PIT: 'Pittsburgh Steelers',
  SF:  'San Francisco 49ers',
  SEA: 'Seattle Seahawks',
  TB:  'Tampa Bay Buccaneers',
  TEN: 'Tennessee Titans',
  WAS: 'Washington Commanders',
};

export const POSITION_NAMES: Record<string, string> = {
  QB:  'Quarterback',
  RB:  'Running Back',
  WR:  'Wide Receiver',
  TE:  'Tight End',
  FB:  'Fullback',
  K:   'Kicker',
  P:   'Punter',
  LS:  'Long Snapper',
  OL:  'Offensive Line',
  OT:  'Offensive Tackle',
  OG:  'Offensive Guard',
  C:   'Center',
  DL:  'Defensive Line',
  DE:  'Defensive End',
  DT:  'Defensive Tackle',
  NT:  'Nose Tackle',
  LB:  'Linebacker',
  ILB: 'Inside Linebacker',
  OLB: 'Outside Linebacker',
  MLB: 'Middle Linebacker',
  DB:  'Defensive Back',
  CB:  'Cornerback',
  S:   'Safety',
  SS:  'Strong Safety',
  FS:  'Free Safety',
  DEF: 'Defense',
  KR:  'Kick Returner',
  PR:  'Punt Returner',
};
